apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: pythonapp          # arbitrary label on deployment
spec:
  replicas: 1
  selector:
    matchLabels:        # labels the replica selector should match
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp      # label for replica selector to match
    spec:
      containers:
      - name: app
        image: pontetcha/imagemypythonapp:latest
        env:
        - name: MARIADDB_USER
          value: admin
        - name: MARIADB_PASSWORD
          value: password
        - name: DB_HOST
          value: 0.0.0.0
        - name: DB_NAME
          value: parc_informatique
        command: ["/bin/sh"]
        args: ["-c", "sleep 10000"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /home/mtn_pvc
          name: app-volume
      - name: db
        image: pontetcha/imagemymariadb:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: password
        - name: MARIADDB_USER
          value: admin
        - name: MARIADB_PASSWORD
          value: password
        - name: DB_HOST
          value: 0.0.0.0
        - name: DB_NAME
          value: parc_informatique
        ports:
        - containerPort: 3606
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-volume
      volumes:
      - name : mariadb-volume
        persistentVolumeClaim:
          claimName: pvc-mariadb
      - name : app-volume
        persistentVolumeClaim:
          claimName: pvc-app
--- 

apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    app: pythonapp
spec:
  type: NodePort
  ports:
   - port: 5000
     protocol: TCP  
  selector:
    app: pythonapp


